[package]
name = "sim-circuit"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.59"
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
strum_macros = "0.26.4"
strum = "0.26.2"
